src/components/Image.jsx
src/components/NavbarC.jsx
src/components/Pisadas.jsx
src/css/NavbarC.css
src/css/Pisadas.css

Se aplica estilos CSS al componente NavbarC

Se aplica estilos CSS al componente NavbarC

---

src/components/NavbarC.jsx
src/components/Pisadas.jsx
src/css/NavbarC.css
src/css/Pisadas.css

Se realiza correcciones de estilos CSS y scroll en version movil

Se realiza correcciones de estilos CSS y scroll en version movil

---

index.html
src/components/FooterC.jsx
src/components/Image.jsx
src/css/FooterC.css
src/main.jsx
src/routes/RoutesViews.jsx

Se realiza footer,se aplica css y se coloca en las rutas

Se realiza footer,se aplica css y se coloca en las rutas

---

package-lock.json
package.json
src/components/FooterC.jsx
src/components/NavbarC.jsx

Se agrega react-icons y se ajusta el sistema de grillas

Se agrega react-icons y se ajusta el sistema de grillas

---

index.html
src/components/FooterC.jsx

Se ajusta el tamaño de los logos,mapas y textos

Se ajusta el tamaño de los logos,mapas y textos

---

src/components/FooterC.jsx
src/pages/RegisterPage.jsx
src/routes/RoutesViews.jsx

Cambios en el footer

---

src/App.jsx
src/components/NavbarC.jsx
src/pages/RegisterPage.jsx
src/routes/RoutesViews.jsx

Creacion de pagina registro y creacion de su respectiva ruta

Creacion de pagina registro y creacion de su respectiva ruta

---

src/components/FooterC.jsx
src/css/FooterC.css
src/css/Reg-Log.css
src/pages/RegisterPage.jsx

Se crea css de register y se modifican los colores de los botones

Se crea css de register y se modifican los colores de los botones

---

src/pages/LoginPage.jsx
src/routes/RoutesViews.jsx

Se crea la page de Login,su respectiva ruta y su css

Se crea la page de Login,su respectiva ruta y su css

---

src/components/MainC.jsx

En la homepage se crea una seccion de publicidad

En la homepage se crea una seccion de publicidad

---

src/components/FooterC.jsx
src/css/FooterC.css

cambios en los divs de publicidad

cambios en los divs de publicidad

---

src/components/MainC.jsx

Cambio en el titulo de la seccion publicidad

Cambio en el titulo de la seccion publicidad

---

src/components/MainC.jsx
src/css/ApiClima.css

Se crea api clima y su css

---

src/components/MainC.jsx
src/css/ApiClima.css

Se corrigen algunos errores en el codigo. Nombres de clases y divs

Se corrigen algunos errores en el codigo. Nombres de clases y divs

---

src/components/CardC.jsx
src/components/FooterC.jsx
src/components/MainC.jsx
src/components/NavbarC.jsx
src/components/Pisadas.jsx
src/css/Carrusel.css
src/css/NavbarC.css
src/css/Productos.css
src/css/Reg-Log.css
src/helpers/titlePages.js
src/pages/HomePage.jsx
src/pages/LoginPage.jsx
src/pages/RegisterPage.jsx

Se crea seleccion de categoria de producto , con su respectivo CSS

Se crea seleccion de categoria de producto , con su respectivo CSS

---

src/components/FooterC.jsx
src/components/MainC.jsx

se arreglo un estilo de css

---

src/components/MainC.jsx
src/css/ApiClima.css

Se añade estilos de CSS a ApiClima

Se añade estilos de CSS a ApiClima

---

.env
src/components/CardC.jsx
src/components/MainC.jsx
src/css/Card.css
src/css/Productos.css
src/helpers/clienteAxios.js

Se crea componente Card, conexion de DB local , Diseño basico de CSS

Se crea componente Card, conexion de DB local , Diseño basico de CSS

---

src/components/MainC.jsx

Se agrega funcionalidades de filtrado en categorias

Se agrega funcionalidades de filtrado en categorias

---

.env
.gitignore
src/components/MainC.jsx
src/css/Card.css

Se crea filtrado de categoria, se realiza paginacion de productos

Se crea filtrado de categoria, se realiza paginacion de productos

---

src/helpers/yupSchema.js
src/pages/RegisterPage.jsx

Se crean funciones en register utilizando la libreria formik y yup

Se crean funciones en register utilizando la libreria formik y yup

---

src/components/MainC.jsx
src/css/Card.css

Se realiza correccion de paginacion y modificacion de css en la card

Se realiza correccion de paginacion y modificacion de css en la card

---

src/css/PlanesPage.css
src/pages/PlanesPage.jsx
src/routes/RoutesViews.jsx

Se crea PlanesPage y su css

---

src/components/ApiClima.jsx
src/components/MainC.jsx
src/css/ApiClima.css

Se genera component ApiClima con Search, y su css

Se genera component ApiClima con Search, y su css

---

src/css/Contacto.css
src/pages/Contacto.jsx
src/routes/RoutesViews.jsx

Se crea page de Contacto y su css

Se crea page de Contacto y su css

---

src/pages/LoginPage.jsx
src/pages/RegisterPage.jsx

al presionar el boton de gmail ahora te redirige a 404

al presionar el boton de gmail ahora te redirige a 404

---

src/helpers/yupSchema.js
src/helpers/yupSchemaLogin.js
src/pages/LoginPage.jsx

se mejoran las validaciones para los formularios de login y registro

se mejoran las validaciones para los formularios de login y registro

---

src/pages/Contacto.jsx

Se realizan validaciones al formulario utilizando Yup y Formik

Se realizan validaciones al formulario utilizando Yup y Formik

---

src/pages/PlanesPage.jsx

Se realiza validacion en PlanesPage con yup y Formik

Se realiza validacion en PlanesPage con yup y Formik

---

src/components/ApiClima.jsx
src/components/MainC.jsx
src/css/ApiClima.css

Se realiza filtro de busqueda en el componente ApiClimaC

Se realiza filtro de busqueda en el componente ApiClimaC

---

src/components/MainC.jsx

Se realiza un codigo mas corto para la filtracion de productos en componente MainC

Se realiza un codigo mas corto para la filtracion de productos en componente MainC

---

src/helpers/yupSchemaLogin.js
src/pages/LoginPage.jsx

se borran comentarios y se cambian las validaciones

se borran comentarios y se cambian las validaciones

---

src/helpers/yupSchema.js
src/pages/RegisterPage.jsx

se borran los comentarios y se cambian las validaciones

se borran los comentarios y se cambian las validaciones

---

src/pages/Contacto.jsx

Se utiliza nodeMailer para enviar mail del formulario de contacto, ademas de cambio en validaciones y RRSS.

Se utiliza nodeMailer para enviar mail del formulario de contacto, ademas de cambio en validaciones y RRSS.

---

src/pages/LoginPage.jsx

Se cambia el texto de un sweet alert

Se cambia el texto de un sweet alert

---

src/pages/LoginPage.jsx

cambio de ruta al loguear a un usuario

cambio de ruta al loguear a un usuario

---

src/helpers/clienteAxios.js
src/pages/AdminProductPage.jsx
src/routes/RoutesViews.jsx

creacion de AdminProduct y su respectiva ruta.

creacion de AdminProduct y su respectiva ruta.

---

src/pages/AdminProductPage.jsx

se trabaja sobre la edicion y eliminacion de productos

se trabaja sobre la edicion y eliminacion de productos

---

src/pages/AdminProductPage.jsx
src/pages/AdminUsersPage.jsx
src/routes/RoutesViews.jsx

se crea AdminUsers y su respectiva ruta. Y se trabaja sobre la edicion y eliminacion de usuarios

se crea AdminUsers y su respectiva ruta. Y se trabaja sobre la edicion y eliminacion de usuarios

---

src/pages/AdminProductPage.jsx

se trabaja sobre la parte de creacion de productos

se trabaja sobre la parte de creacion de productos

---

src/pages/Contacto.jsx

Se cambia direccion en el mapa

Se cambia direccion en el mapa

---

package-lock.json
package.json
src/css/CrearTurno.css
src/pages/CrearTurno.jsx
src/pages/TurnosList.jsx
src/pages/TurnosPage.jsx
src/routes/RoutesViews.jsx

Se crea turnosPage, y su css

---

src/pages/AdminProductPage.jsx

se agregan manejadores de errores

se agregan manejadores de errores

---

src/components/ApiClima.jsx
src/pages/AdminProductPage.jsx
src/pages/Contacto.jsx
src/pages/CrearTurno.jsx
src/pages/LoginPage.jsx
src/pages/PlanesPage.jsx

se quitan comentarios y consoles.log

se quitan comentarios y consoles.log

---

src/pages/AdminUsersPage.jsx

se agregan sweet alerts y se agrega un drop para elegir el role a la hora de editar

se agregan sweet alerts y se agrega un drop para elegir el role a la hora de editar

---

src/pages/AdminPage.jsx
src/pages/AdminProductPage.jsx

se utilizan sweet alerts,se cambia de posicion el boton de crear producto y se agrega un drop para elegir la categoria

se utilizan sweet alerts,se cambia de posicion el boton de crear producto y se agrega un drop para elegir la categoria

---

src/pages/AdminProductPage.jsx
src/pages/AdminUsersPage.jsx

se cambia el confirm y los alert de errores por sweet alerts

se cambia el confirm y los alert de errores por sweet alerts

---

src/components/ApiClima.jsx
src/components/MainC.jsx

Se añade la funcion del search en ApiClima, y en MainC se hace la conexion para el mismo

Se añade la funcion del search en ApiClima, y en MainC se hace la conexion para el mismo

---

src/css/ProfesionalesPage.css
src/pages/ProfesionalesPage.jsx

Se crea reseñas en ProfesionalesPage y se añade reseñas en su css

Se crea reseñas en ProfesionalesPage y se añade reseñas en su css

---

src/pages/AdminProductPage.jsx

se trabaja sobre las imagenes en la edicion y creacion de productos

se trabaja sobre las imagenes en la edicion y creacion de productos

---

src/helpers/clienteAxios.js

se cambia valor de entorno por deploy de backend

se cambia valor de entorno por deploy de backend

---

src/pages/DetalleProducto.jsx

se cambia la ruta para obtener un producto

se cambia la ruta para obtener un producto

---

src/pages/AdminProductPage.jsx
src/pages/AdminUsersPage.jsx

se realiza validacion en los formularios de editar y crear

se realiza validacion en los formularios de editar y crear

---

src/pages/AdminUsersPage.jsx

se realizan cambios en los estados del usuario cuando esta habilitado o deshabilitado

se realizan cambios en los estados del usuario cuando esta habilitado o deshabilitado

---

src/helpers/clienteAxios.js

Se modifica variable de entorno en ClienteAxios para el uso del deploy

Se modifica variable de entorno en ClienteAxios para el uso del deploy

---

src/components/NavbarC.jsx
src/pages/AdminProfesionales.jsx

se realiza la edicion y creacion de horarios

se realiza la edicion y creacion de horarios

---

src/components/NavbarC.jsx
src/css/SobreNosotros.css
src/pages/SobreNosotros.jsx

Se hace cambios en la page SobreNosotros, y sobreNosotrosCSS

Se hace cambios en la page SobreNosotros, y sobreNosotrosCSS

---

src/pages/AdminProductPage.jsx
src/pages/AdminProfesionales.jsx

se agrega spiner y se cambian los location.reload

se agrega spiner y se cambian los location.reload

---

src/components/CardC.jsx
src/pages/AdminPageComentarios.jsx
src/pages/AdminProfesionales.jsx

se cambia de color los botones en los form de profesionales

se cambia de color los botones en los form de profesionales

---

src/css/ProfesionalesPage.css
src/helpers/clienteAxios.js
src/pages/Contacto.jsx
src/pages/PlanesPage.jsx
src/pages/ProfesionalesPage.jsx

Correcciones proyect

---

src/pages/AdminProfesionales.jsx

se agrega otra validacion a formularios de editar y crear

se agrega otra validacion a formularios de editar y crear

---

src/css/ProfesionalesPage.css
src/pages/Contacto.jsx
src/pages/PlanesPage.jsx

Se agrega sweet alert en los formularios de Planes, y Contacto, y se aplica un cambio de css en ProfesionalesPage

Se agrega sweet alert en los formularios de Planes, y Contacto, y se aplica un cambio de css en ProfesionalesPage

---

src/components/CardC.jsx
src/css/CrearTurno.css
src/pages/CrearTurno.jsx
src/pages/ProfesionalesPage.jsx

correcion de margenes y botones en cardC,crearTurno y ProfesionalesPage

correcion de margenes y botones en cardC,crearTurno y ProfesionalesPage

---

src/pages/AdminPageComentarios.jsx
src/pages/PlanesPage.jsx

se quita etiqueta p en adminPageComentarios

se quita etiqueta p en adminPageComentarios

---

src/pages/MisDatosPage.jsx

se añade validacion con yup en misDatosPage

se añade validacion con yup en misDatosPage
